### ISSUE TITLE
Inserimento publiccode.yml nella code base

### ISSUE THREAD

**Issue by libremente** [SITA-RegionePiemonte/USC#3]
Buongiorno @silettog,
una volta concluse le operazioni di onboarding è necessario compilare il file `publiccode.yml` (si veda il formato [qui](https://docs.italia.it/italia/developers-italia/publiccodeyml-en/en/core-0.2-it-0.2/)) in modo tale da essere aderenti alle [linee guida](https://docs.italia.it/italia/developers-italia/lg-acquisizione-e-riuso-software-per-pa-docs/it/bozza/index.html) ed essere indicizzati all'interno del portale di [Developers Italia](https://developers.italia.it). 
Per facilitare la creazione di tale file è disponibile l'[editor](https://publiccode-editor.developers.italia.it/). 
Ovviamente per qualsiasi tipo di informazione resto a disposizione.
Grazie mille!

**Comment by silettog** [comment]
buongiorno
questo repo (USC) non è destinato (almeno per ora) alla pubblicazione su Developers
grazie
